linters:
  enable-all: true
  disable:
    - depguard # Checks package imports are in a list of acceptable packages
    - godot # Checks if all comments ends with a period
    - nlreturn # Checks if all return statements have a new line before them
    - wsl # Checks for missing whitespaces
    - gomnd # The linter has been renamed and replaced by mnd
    - execinquery # It's deprecated the repository of the linter has been archived by the owner
