// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rios0rios0/terra/internal"
	"github.com/rios0rios0/terra/internal/domain/commands"
	"github.com/rios0rios0/terra/internal/domain/entities"
	"github.com/rios0rios0/terra/internal/infrastructure/controllers"
	"github.com/rios0rios0/terra/internal/infrastructure/repositories"
)

// Injectors from wire.go:

func injectAppContext() entities.AppContext {
	deleteCacheCommand := commands.NewDeleteCacheCommand()
	deleteCacheController := controllers.NewDeleteCacheController(deleteCacheCommand)
	stdShellRepository := repositories.NewStdShellRepository()
	formatFilesCommand := commands.NewFormatFilesCommand(stdShellRepository)
	settings := entities.NewSettings()
	v := controllers.NewDependencies(settings)
	formatFilesController := controllers.NewFormatFilesController(formatFilesCommand, v)
	installDependenciesCommand := commands.NewInstallDependenciesCommand()
	installDependenciesController := controllers.NewInstallDependenciesController(installDependenciesCommand, v)
	v2 := controllers.NewControllers(deleteCacheController, formatFilesController, installDependenciesController)
	appInternal := internal.NewAppInternal(v2)
	appContext := newAppContext(appInternal)
	return appContext
}

func injectRootController() entities.Controller {
	installDependenciesCommand := commands.NewInstallDependenciesCommand()
	stdShellRepository := repositories.NewStdShellRepository()
	formatFilesCommand := commands.NewFormatFilesCommand(stdShellRepository)
	settings := entities.NewSettings()
	cli := entities.NewCLI(settings)
	runAdditionalBeforeCommand := commands.NewRunAdditionalBeforeCommand(settings, cli, stdShellRepository)
	runFromRootCommand := commands.NewRunFromRootCommand(installDependenciesCommand, formatFilesCommand, runAdditionalBeforeCommand, stdShellRepository)
	v := controllers.NewDependencies(settings)
	runFromRootController := controllers.NewRunFromRootController(runFromRootCommand, v)
	controller := newRootController(runFromRootController)
	return controller
}

// wire.go:

func newAppContext(appInternal *internal.AppInternal) entities.AppContext {
	return appInternal
}

func newRootController(rootController *controllers.RunFromRootController) entities.Controller {
	return rootController
}
